### ISSUE TITLE
Docker Hub tags missing for elixir 1.7.4 build

### ISSUE THREAD

**Issue by dhedlund** [bitwalker/alpine-elixir#28]
It looks like a new docker image was built a few days ago for the [1.7.4](https://github.com/bitwalker/alpine-elixir/pull/27) version bump, but only the "latest" tag shows as updated on docker hub: https://hub.docker.com/r/bitwalker/alpine-elixir/tags/

Attempting to use the tag in a Dockerfile results in an error:

```
$ docker build .
Sending build context to Docker daemon  2.353MB
Step 1/2 : FROM bitwalker/alpine-elixir:1.7.4
manifest for bitwalker/alpine-elixir:1.7.4 not found
```

**Comment by cblage** [comment]
Same here

**Comment by prodis** [comment]
@bitwalker Could you please create the `1.7.4` tag on Docker Hub in order to avoid us to referrer to `latest` tag in our Docker images?

**Comment by bitwalker** [comment]
Seems like even though the tag was pushed the build never got triggered. I'm pushing it now.

**Comment by prodis** [comment]
Thanks!
