### ISSUE TITLE
Manifest not found error for 1.9.1

### ISSUE THREAD

**Issue by jmedding** [bitwalker/alpine-elixir#44]
I'm just starting on the Docker & Releases journey.  I get:

`Step 1/7 : FROM bitwalker/alpine-elixir:1.9.1 as build`
`manifest for bitwalker/alpine-elixir:1.9.1 not found`

with the following Dockerfile

```
FROM bitwalker/alpine-elixir:1.9.1 as build

COPY config ./config
COPY lib ./lib
COPY priv ./priv
COPY mix.exs .
COPY mix.lock .


RUN export MIX_ENV=prod && \
    mix deps.get && \
    mix release
```

using 1.9 instead of 1.9.1 works normally

**Comment by geofflane** [comment]
It's not on dockerhub yet, or more accurately. The 1.9.1 build isn't tagged 1.9.1, but only tagged latest.

**Comment by rsilvestre** [comment]
@bitwalker hi, is it possible to build the version 1.9.1 and tag it on dockerhub ?

**Comment by bitwalker** [comment]
Pushing the release now!
