### ISSUE TITLE
Obsolete?

### ISSUE THREAD

**Issue by arjan** [bitwalker/alpine-elixir#57]
Now that we have [official Elixir docker builds](https://hub.docker.com/r/hexpm/elixir/tags), also for Alpine, maybe we should direct users there instead of maintaining this docker image?

**Comment by bitwalker** [comment]
I’m fine with that, seems like they have alpine images, so that’s one less thing to maintain :)

**Comment by IceDragon200** [comment]
@bitwalker Sorry to ask this of you, but could you continue supporting your image and update to elixir to 1.10.x, the official images are only built against erlang21, and we need 22 at work

**Comment by bitwalker** [comment]
I'll continue maintaining these for a while longer, but if it looks like people have switched to the official images, I'll probably stop actively publishing new releases except when I need them personally.
