### ISSUE TITLE
alpine-elixir:1.10.4 dockerhub image is using 1.11.0

### ISSUE THREAD

**Issue by DanielKulesza** [bitwalker/alpine-elixir#62]
When trying to use the alpine-elixir:1.10.4 image, there were a lot of new warnings and errors being raised during compilation. It looks like this was a result of the 1.10.4 docker image being upgraded to use 1.11.0 but still being tagged 1.10.4 https://github.com/bitwalker/alpine-elixir/pull/61. 

https://hub.docker.com/layers/bitwalker/alpine-elixir/1.10.4/images/sha256-71458526b89e2f01d0a2ac05ea825ce72f787aa07f49c09b33eb218f5d26113d?context=explore

**Comment by bitwalker** [comment]
Hmm, that should not have happened, I’ll take a look and see if I can figure out what went wrong there.

As I’ve mentioned in many places before, this is a great example of why I believe strongly that teams should maintain their own repo of images, even if originally pulled from Docker Hub - it’s just all too easy for a mistake like this to cause real pain.

**Comment by bitwalker** [comment]
I'm rebuilding the 1.10.4 image now and will re-publish it shortly. A new 1.11.0 image will be published shortly after.
