### ISSUE TITLE
Publish dockerhub tag 1.11.1

### ISSUE THREAD

**Issue by rupurt** [bitwalker/alpine-elixir#66]
Currently only 1.11.0 is published on dockerhub.

It would also be nice to add git tags for the releases. I can work on adding a Github action to automate this if you would like.

**Comment by frahugo** [comment]
I agree. `latest` as a tag is not enough on Docker Hub. In my docker file, I want to have a dependency on `1.11.1` and not `latest` as I need more control on the version of elixir used by my app. Same thing with `alpine-elixir-phoenix`.

**Comment by bitwalker** [comment]
1.11.3 is tagged and published
