### ISSUE TITLE
libcurl needs upgrading

### ISSUE THREAD

**Issue by joshuataylor** [bitwalker/alpine-elixir#9]
libcurl 7.55.0 is out, 7.54.x is used.

**Comment by bitwalker** [comment]
Please only report package upgrades if they are available in the stable release of Alpine - or edge if it's a critical security fix. If a package isn't available via the package repository, I'm not going to build it by hand (other than Elixir and Erlang).

**Comment by joshuataylor** [comment]
It is available.

Doing `          command: apk add --no-cache curl` fails, so I just do `apk --update upgrade`

**Comment by bitwalker** [comment]
Your original message specified 7.55.1, looks like you updated it though, 7.55.1 isn't available yet (assuming it's a valid version). I'll push an update tonight anyway because a bigger security fix is available for pcre

**Comment by joshuataylor** [comment]
Yeah sorry, I meant 7.55.1, but that isn't out yet in alpine, only 7.55.0. Appreciate it, this image is great! Cheers!

**Comment by bitwalker** [comment]
New version of 1.5.1 is up with 7.55.0 :)
